# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                ("bank_name", models.CharField(max_length=30, verbose_name="bank_name")),
                ("bank_url", models.URLField(verbose_name="bank_url")),
                ("bank_login_url", models.URLField(verbose_name="bank_login_url")),
                (
                    "bank_tech_support_url",
                    models.URLField(null=True, verbose_name="bank_tech_support_url"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankUserAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=30, null=True, verbose_name="username"),
                ),
                (
                    "password",
                    models.CharField(max_length=250, null=True, verbose_name="password"),
                ),
                ("status", models.BooleanField(null=True, verbose_name="status")),
                (
                    "bank_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_user_account",
                        to="bank_account.bankprofile",
                    ),
                ),
                ("clients", models.ManyToManyField(to="client.client")),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccountItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                ("label", models.CharField(max_length=30, verbose_name="label")),
                (
                    "bank_account_type",
                    models.CharField(
                        choices=[
                            ("checking_account", "Checking Account"),
                            ("saving_account", "Saving Account"),
                            ("credit_card", "CreditCard"),
                            ("loan", "Loan"),
                        ],
                        max_length=50,
                        verbose_name="bank_account_type",
                    ),
                ),
                (
                    "bank_user_account",
                    models.ManyToManyField(to="bank_account.bankuseraccount"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
