# Generated by Django 4.1.2 on 2022-10-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccountitem",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is_deleted"),
        ),
        migrations.AddField(
            model_name="bankprofile",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is_deleted"),
        ),
        migrations.AddField(
            model_name="bankuseraccount",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is_deleted"),
        ),
    ]
