# Generated by Django 4.0.6 on 2022-07-22 12:48

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('label', models.CharField(max_length=30, null=True, verbose_name='label')),
                ('service_name', models.CharField(choices=[('office_365', 'Office 365'), ('support_system', 'Support System'), ('focalboard', 'Focalboard System'), ('portal_system', 'Portal System'), ('bookkeeper_checklist_app', 'Bookkeeper Checklist App'), ('quickbooks_online', 'Quickbooks Online'), ('mailchimp', 'Mailchimp'), ('crm', 'CRM'), ('blog', 'Blog'), ('kennected', 'Kennected'), ('shared_accounts', 'Shared Accounts')], max_length=35, verbose_name='service_name')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('password', models.CharField(max_length=250, verbose_name='password')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
