# Generated by Django 4.1.3 on 2022-11-21 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_remove_client_company_services"),
        ("company_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyservice",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company_services",
                to="client.client",
            ),
        ),
    ]
