# Generated by Django 4.1.3 on 2022-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_services", "0002_companyservice_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyservice",
            name="service_name",
            field=models.CharField(
                choices=[
                    ("office_365", "Office 365"),
                    ("support_system", "Support System"),
                    ("focalboard", "Focalboard System"),
                    ("portal_system", "Portal System"),
                    ("bookkeeper_checklist_app", "Bookkeeper Checklist App"),
                    ("quickbooks_online", "Quickbooks Online"),
                    ("mailchimp", "Mailchimp"),
                    ("crm", "CRM"),
                    ("blog", "Blog"),
                    ("kennected", "Kennected"),
                    ("shared_accounts", "Shared Accounts"),
                ],
                max_length=35,
                verbose_name="service name",
            ),
        ),
    ]
