# Generated by Django 4.0.6 on 2022-07-22 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=80, null=True, verbose_name='title')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('note', models.TextField(null=True, verbose_name='note')),
                ('task_type', models.CharField(choices=[('no_type', 'No Type'), ('recurring', 'Recurring'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One Time'), ('urgent', 'Urgent')], default='no_type', max_length=20, verbose_name='task_type')),
                ('task_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In progress'), ('past_due', 'Past Due'), ('complete', 'Complete')], default='not_started', max_length=20, verbose_name='task_status')),
                ('due_date', models.DateField(verbose_name='due_date')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('task_items', models.ManyToManyField(to='tasks.taskitem')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
