# Generated by Django 4.1 on 2022-08-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskitem",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is_completed"),
        ),
    ]
