# Generated by Django 4.1.1 on 2022-09-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_taskitem_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskitem",
            name="hints",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="hints"
            ),
        ),
    ]
