# Generated by Django 4.0.6 on 2022-07-22 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('account_name', models.CharField(max_length=50, null=True, verbose_name='account_name')),
                ('account_email', models.EmailField(max_length=50, null=True, verbose_name='account_email')),
                ('account_url', models.URLField(max_length=50, null=True, verbose_name='account_url')),
                ('account_username', models.CharField(max_length=30, null=True, verbose_name='account_username')),
                ('account_password', models.CharField(max_length=250, null=True, verbose_name='account_password')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='last_modified_date')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientBusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='phone')),
                ('website_url', models.URLField(max_length=50, null=True, verbose_name='website_url')),
                ('address', models.CharField(max_length=50, null=True, verbose_name='address')),
                ('contact', models.CharField(max_length=50, null=True, verbose_name='contact')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict, null=True, verbose_name='metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='email')),
                ('industry', models.CharField(max_length=50, null=True, verbose_name='industry')),
                ('business_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='client.clientbusinessprofile')),
                ('client_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='client.clientaccount')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
