# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("important_contact", "0001_initial"),
        ("company_services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                ("name", models.CharField(max_length=50, null=True, verbose_name="name")),
                (
                    "email",
                    models.EmailField(max_length=50, null=True, verbose_name="email"),
                ),
                (
                    "industry",
                    models.CharField(max_length=50, null=True, verbose_name="industry"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is_active")),
                (
                    "company_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="company_logo",
                    ),
                ),
                (
                    "company_services",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="client",
                        to="company_services.companyservice",
                    ),
                ),
                (
                    "important_contact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="client",
                        to="important_contact.importantcontact",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
