# Generated by Django 4.1.1 on 2022-09-26 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_company_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportantContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "contact_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="contact_fields",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="client",
            name="business_profile",
        ),
        migrations.DeleteModel(
            name="ClientBusinessProfile",
        ),
        migrations.AddField(
            model_name="client",
            name="important_contact",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client",
                to="client.importantcontact",
            ),
        ),
    ]
