# Generated by Django 4.1.2 on 2022-10-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_importantcontact_remove_client_business_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is_deleted"),
        ),
        migrations.AddField(
            model_name="clientaccount",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is_deleted"),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="is_deleted"),
        ),
    ]
