# Generated by Django 4.1.2 on 2022-10-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0007_remove_bookkeeper_clients"),
        ("client", "0004_client_is_deleted_clientaccount_is_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="bookkeeper",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client",
                to="bookkeeper.bookkeeper",
            ),
        ),
    ]
