# Generated by Django 4.1.2 on 2022-10-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_client_bookkeeper"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="bookkeeper",
        ),
    ]
