# Generated by Django 4.1.2 on 2022-10-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_remove_client_bookkeeper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client",
                to="client.clientaccount",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="important_contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client",
                to="client.importantcontact",
            ),
        ),
    ]
