# Generated by Django 4.1.2 on 2022-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_alter_client_client_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="company_logo"
            ),
        ),
    ]
