# Generated by Django 4.1.3 on 2022-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_alter_client_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientaccount",
            name="account_email",
            field=models.EmailField(
                max_length=50, null=True, verbose_name="account email"
            ),
        ),
        migrations.AlterField(
            model_name="clientaccount",
            name="account_name",
            field=models.CharField(
                max_length=50, null=True, verbose_name="account name"
            ),
        ),
        migrations.AlterField(
            model_name="clientaccount",
            name="account_password",
            field=models.CharField(
                max_length=250, null=True, verbose_name="account password"
            ),
        ),
        migrations.AlterField(
            model_name="clientaccount",
            name="account_url",
            field=models.URLField(max_length=50, null=True, verbose_name="account url"),
        ),
        migrations.AlterField(
            model_name="clientaccount",
            name="account_username",
            field=models.CharField(
                max_length=30, null=True, verbose_name="account username"
            ),
        ),
    ]
