# Generated by Django 4.1.3 on 2022-11-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0009_alter_clientaccount_account_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="importantcontact",
            name="contact_fields",
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="city"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="company_name",
            field=models.CharField(
                blank=True, max_length=60, null=True, verbose_name="company name"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="email"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="phone",
            field=models.CharField(
                blank=True, max_length=80, null=True, verbose_name="phone"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="postcode",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="postcode"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="state",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="state"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="street_address",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="street address"
            ),
        ),
        migrations.AddField(
            model_name="importantcontact",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="website"),
        ),
    ]
