# Generated by Django 4.1 on 2022-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookkeeper",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="profile_picture",
            ),
        ),
    ]
