# Generated by Django 4.0.6 on 2022-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookkeeper', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookkeeper',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
