# Generated by Django 4.1 on 2022-08-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0003_bookkeeper_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookkeeper",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "permissions": [("bookkeeper_user", "Bookkeeper User")],
            },
        ),
    ]
