# Generated by Django 4.1.2 on 2022-10-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0004_alter_bookkeeper_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookkeeper",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="bio"),
        ),
    ]
