# Generated by Django 4.1.2 on 2022-10-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0006_bookkeeper_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookkeeper",
            name="clients",
        ),
    ]
