# Generated by Django 4.1.2 on 2022-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_remove_client_bookkeeper"),
        ("bookkeeper", "0007_remove_bookkeeper_clients"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookkeeper",
            name="clients",
            field=models.ManyToManyField(to="client.client"),
        ),
    ]
