# Generated by Django 4.1.3 on 2022-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0008_bookkeeper_clients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookkeeper",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, null=True, verbose_name="slug"
            ),
        ),
    ]
