# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportantContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="company name"
                    ),
                ),
                ("contact_label", models.CharField(max_length=50, verbose_name="label")),
                (
                    "contact_description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "contact_first_name",
                    models.CharField(max_length=50, verbose_name="first name"),
                ),
                (
                    "contact_last_name",
                    models.CharField(max_length=50, verbose_name="last name"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="contact email"),
                ),
                (
                    "contact_city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "contact_state",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="state"
                    ),
                ),
                (
                    "contact_postcode",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="postcode"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=80, verbose_name="phone"),
                ),
                (
                    "contact_website",
                    models.URLField(blank=True, null=True, verbose_name="website"),
                ),
                (
                    "contact_notes",
                    models.TextField(blank=True, null=True, verbose_name="notes"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
