# Generated by Django 4.1.1 on 2022-10-04 15:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task", "0002_task_start_date"),
        ("client", "0003_importantcontact_remove_client_business_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The Job Title", max_length=70, verbose_name="title"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Note(s) for this job (optional)",
                        null=True,
                        verbose_name="note",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("no_type", "No Type"),
                            ("recurring", "Recurring"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                            ("urgent", "Urgent"),
                        ],
                        default="no_type",
                        help_text="Type of this job, Recurring, Weekly, Urgent,..etc",
                        max_length=20,
                        verbose_name="job_type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("past_due", "Past Due"),
                            ("complete", "Complete"),
                            ("archive", "Archive"),
                        ],
                        default="not_started",
                        help_text="Status of this job, Not Started, In Progress, Done,..etc",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="The client this job belong to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="client.client",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        help_text="Tasks of this job", to="task.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
