# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task", "0001_initial"),
        ("bookkeeper", "0001_initial"),
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job Title", max_length=100, verbose_name="title"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=250, null=True, verbose_name="slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the job",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for this job",
                        null=True,
                        verbose_name="due date",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("no_type", "No Type"),
                            ("recurring", "Recurring"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                            ("urgent", "Urgent"),
                        ],
                        help_text="Type of this job, Recurring, Weekly, Urgent,..etc",
                        max_length=20,
                        verbose_name="job type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("past_due", "Past Due"),
                            ("complete", "Complete"),
                            ("archive", "Archive"),
                        ],
                        help_text="Status of this job, Not Started, In Progress, Done,..etc",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Note(s) for this job (optional)",
                        null=True,
                        verbose_name="note",
                    ),
                ),
                (
                    "bookkeeper",
                    models.ForeignKey(
                        blank=True,
                        help_text="Bookkeeper of the job",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="bookkeeper.bookkeeper",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client this job belong to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="jobs",
                        to="client.client",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(help_text="Tasks of this job", to="task.task"),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
