# Generated by Django 4.1.1 on 2022-10-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("past_due", "Past Due"),
                    ("complete", "Complete"),
                    ("archive", "Archive"),
                ],
                help_text="Status of this job, Not Started, In Progress, Done,..etc",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
