# Generated by Django 4.1.3 on 2022-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_job_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, null=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("no_type", "No Type"),
                    ("recurring", "Recurring"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                    ("one_time", "One Time"),
                    ("urgent", "Urgent"),
                ],
                help_text="Type of this job, Recurring, Weekly, Urgent,..etc",
                max_length=20,
                verbose_name="job type",
            ),
        ),
    ]
