# Generated by Django 4.1.3 on 2022-11-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookkeeper", "0009_alter_bookkeeper_slug"),
        ("jobs", "0008_job_slug_alter_job_job_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="bookkeeper",
            field=models.ForeignKey(
                blank=True,
                help_text="Bookkeeper of the job",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="bookkeeper.bookkeeper",
            ),
        ),
    ]
