# Generated by Django 4.1.3 on 2022-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_alter_job_bookkeeper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(
                help_text="Job Title", max_length=100, verbose_name="title"
            ),
        ),
    ]
