# Generated by Django 4.1.3 on 2022-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_alter_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
    ]
