# Generated by Django 4.1.3 on 2022-11-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_job_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Description of the job",
                null=True,
                verbose_name="description",
            ),
        ),
    ]
