# Generated by Django 4.1.3 on 2022-11-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_alter_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Due date for this job",
                null=True,
                verbose_name="due date",
            ),
        ),
    ]
