# Generated by Django 4.1.3 on 2022-11-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_job_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Note(s) for this job (optional)",
                null=True,
                verbose_name="note",
            ),
        ),
    ]
