# Generated by Django 4.1.3 on 2022-11-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0010_remove_importantcontact_contact_fields_and_more"),
        ("jobs", "0014_alter_job_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Client this job belong to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="client.client",
            ),
        ),
    ]
