# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import documents.models.document
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("task", "0001_initial"),
        ("client", "0001_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documents",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                ("title", models.CharField(max_length=70, verbose_name="title")),
                (
                    "document_section",
                    models.CharField(
                        blank=True,
                        choices=[("client", "Client"), ("job", "Job"), ("task", "Task")],
                        max_length=15,
                        null=True,
                        verbose_name="document section",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        upload_to=documents.models.document.saved_document_file_path,
                        verbose_name="document file",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="client.client",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="jobs.job",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="task.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
