# Generated by Django 4.1.1 on 2022-09-26 14:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=80, null=True, verbose_name="title"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="is_completed"),
                ),
                (
                    "hints",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="hints"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="due_date")),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
