# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                ("title", models.CharField(max_length=80, null=True, verbose_name="title")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_type", "No Type"),
                            ("recurring", "Recurring"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                            ("urgent", "Urgent"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="is completed"),
                ),
                (
                    "hints",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="hints"
                    ),
                ),
                (
                    "additional_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="additional notes"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="start date"),
                ),
                ("due_date", models.DateField(verbose_name="due date")),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
