# Generated by Django 4.1.1 on 2022-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(null=True, verbose_name="start_date"),
        ),
    ]
