# Generated by Django 4.1.3 on 2022-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_task_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(verbose_name="due date"),
        ),
        migrations.AlterField(
            model_name="task",
            name="is_completed",
            field=models.BooleanField(default=False, verbose_name="is completed"),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(null=True, verbose_name="start date"),
        ),
    ]
