# Generated by Django 4.1.3 on 2022-11-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_alter_task_due_date_alter_task_is_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(blank=True, null=True, verbose_name="notes"),
        ),
        migrations.AlterField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="start date"),
        ),
    ]
