# Generated by Django 4.1.3 on 2022-11-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0005_task_notes_alter_task_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_type", "No Type"),
                    ("recurring", "Recurring"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                    ("one_time", "One Time"),
                    ("urgent", "Urgent"),
                ],
                max_length=15,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
