# Generated by Django 4.0.6 on 2022-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('bookkeeper', 'Bookkeeper'), ('assistant', 'Assistant')], max_length=15, verbose_name='user type'),
        ),
    ]
