# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Manager",
            fields=[],
            options={
                "permissions": [("manager_user", "Manager User")],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.customuser",),
        ),
    ]
