# Generated by Django 4.1 on 2022-08-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={
                "permissions": [
                    ("can_view_dashboard", "Can View Dashboard"),
                    ("manager_user", "Manager User"),
                ]
            },
        ),
    ]
