# Generated by Django 4.1 on 2022-08-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_manager_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manager",
            options={"permissions": [("manager_user", "Manager User")]},
        ),
    ]
