# Generated by Django 4.1 on 2022-08-05 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assistant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
