# Generated by Django 4.1 on 2022-08-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0003_assistant_profile_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assistant",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "permissions": [
                    ("assistant_user", "Assistant User"),
                    ("can_access_bookkeeper", "Can access bookkeeper account details"),
                    ("can_edit_bookkeeper", "Can edit bookkeeper account details"),
                    ("can_access_client", "Can access client(s) account details"),
                ],
            },
        ),
    ]
