# Generated by Django 4.1.3 on 2022-11-21 12:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="metadata"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="is_deleted"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created_at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="updated_at"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        default=None, null=True, verbose_name="deleted_at"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(max_length=50, null=True, verbose_name="account name"),
                ),
                (
                    "account_email",
                    models.EmailField(
                        max_length=50, null=True, verbose_name="account email"
                    ),
                ),
                (
                    "account_url",
                    models.URLField(max_length=50, null=True, verbose_name="account url"),
                ),
                (
                    "account_username",
                    models.CharField(
                        max_length=30, null=True, verbose_name="account username"
                    ),
                ),
                (
                    "account_password",
                    models.CharField(
                        max_length=250, null=True, verbose_name="account password"
                    ),
                ),
                (
                    "last_modified_date",
                    models.DateTimeField(auto_now=True, verbose_name="last_modified_date"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="client_account",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
